# https://jekyllrb.com/docs/configuration/
exclude:
  - CNAME
  - LICENSE
  - README.md
  - docker-compose.yml
  - node_modules
  - package.json
  - yarn.lock

timezone: Asia/Tokyo

future: true

permalink: /memo/:title.html

plugins:
  - jekyll-sitemap

# https://github.com/jekyll/jekyll-sass-converter#configuration-options
sass:
  style: compressed

# sasaplus1/memo
name: memo

url: https://memo.sasaplus1.com
