version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:pages
    container_name: memo
    command:
      - tail
      - -f
      - /dev/null
    init: true
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
