name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: ${{ github.repository }}/.github/workflows/caller-deploy.yml@main
        with:
          ref: master
