name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/caller-deploy.yml@main
        with:
          ref: main
