name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        default: main
        description: Target reference
        required: true
        type: string

jobs:
  deploy:
    uses: sasaplus1/memo/.github/workflows/caller-deploy.yml@${{ github.event.inputs.ref }}
    with:
      ref: ${{ github.event.inputs.ref }}
