name: deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: master
        type: string

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: ${{ github.repository }}/.github/workflows/call-deploy.yml@main
        with:
          ref: ${{ github.event.inputs.ref }}
