name: manually deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        default: main
        description: target ref
        required: true
        type: string

jobs:
  manually-deploy:
    uses: sasaplus1/memo/.github/workflows/caller-deploy.yml@${{ github.event.inputs.ref }}
    with:
      ref: ${{ github.event.inputs.ref }}
