name: manually deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: master
        type: string

jobs:
  manually-deploy:
    name: manually deploy
    runs-on: ubuntu-latest
    steps:
      - uses: ${{ github.repository }}/.github/workflows/caller-deploy.yml@main
        with:
          ref: ${{ github.event.inputs.ref }}
