name: manually deploy

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: main
        type: string

jobs:
  manually-deploy:
    name: manually deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: .github/workflows/caller-deploy.yml
        with:
          ref: ${{ github.event.inputs.ref }}
