name: test

on:
  - push
  - pull_request

jobs:
  lint:
    name: lint
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
